workflows:
  ios-release:
    name: iOS release workflow
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Install specific Flutter version
        script: |
          git clone https://github.com/flutter/flutter.git /tmp/flutter
          cd /tmp/flutter
          git checkout 3.8.0-24.0.dev  # Укажите нужную версию Flutter с Dart 3.8.0
          export PATH="$PATH:/tmp/flutter/bin"
      - name: Get dependencies
        script: flutter packages get
      - name: Build iOS app
        script: flutter build ios --release
